routes:
  /:
    data: page.home
    template: home
  /news/rss/:
    template: news/rss
    content_type: text/xml

collections:
  /news/:
    permalink: /news/{slug}/
    template: index
    filter: tag:news+tag:-resource
  /resources/:
    permalink: /resources/{slug}/
    template: resources
    filter: tag:resource+tag:-news

taxonomies:
  tag: /tag/{slug}/
