routes:
  /:
    data: page.home
    template: home

collections:
  /news/:
    permalink: /news/{slug}/
    template: index
    filter: tag:news+tag:-resources
  /resources/:
    permalink: /resources/{slug}/
    template: resources
    filter: tag:resources+tag:-news

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
