name: Deploy Theme
on:
  push:
    branches:
      - master
    paths:
      - 'theme/**'
      - '.github/workflows/deploy-theme.yml'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    environment: production
    defaults:
      run:
        working-directory: theme
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn pretest
      - run: yarn test
      - run: yarn zip
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.4.1
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          file: theme/dist/new-self.zip
